/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectogrupo1.prestamo;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.javatuples.Triplet;
import proyectogrupo1.ConexionSQL;
import proyectogrupo1.cliente.SqlCrudClienteByCI;
import proyectogrupo1.cliente.Cliente;
import proyectogrupo1.cliente.GUIActualizar;
import proyectogrupo1.libro.Ejemplar;
import proyectogrupo1.libro.Libro;
import proyectogrupo1.libro.SqlCrudEjemplar;
import proyectogrupo1.libro.SqlCrudEjemplarByLibroId;
import proyectogrupo1.libro.SqlCrudLibroByTitulo;

/**
 *
 * @author denni
 */
public class InterfazPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrestamos
     */
    //Variables para la cancelación de préstamos 
    private Cliente clientePrestamo;
    private Libro libroPrestamo;
    private List<Ejemplar> ejemplaresEncontrados;
    private Ejemplar ejemplarPrestamo;
    
    private Cliente clienteCancelar;
    private Ejemplar ejemplarCancelar;
    
    String cedulaCancelar;
    String codigoCancelar;
    List<Prestamo> prestamosCancelar;
    
    //Variables para la modificación 
    String buscarCedula;
    String buscarCodigoLibro;
    int verificacionConsulta;

    Boolean clienteValido = false;
    Boolean libroExistente = false;
    String auxiliarCodigoCliente, auxiliarCodigoLibro;

    public InterfazPrestamos() {
        initComponents();
        try {
            jTFCodigoP.setText(String.valueOf(Prestamo.sQLIndexIdPrestamo.peek()));
        } catch (SQLException ex) {
            Logger.getLogger(InterfazPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //FUNCION PARA CALCULAR MULTAS POR RETRASO DE ENTREGA
    public String calcularMulta(String dayBefore) {
        dayBefore = String.format("%." + 10 + "s", dayBefore);

        LocalDate Before = LocalDate.parse(dayBefore, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        LocalDate After = LocalDate.now();

        long diff = ChronoUnit.DAYS.between(Before, After);
        return "" + diff * 1.5 + "$ (" + diff + " días de retraso)";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        nombreCliente = new javax.swing.JTextField();
        apellidoCliente = new javax.swing.JTextField();
        direccionCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        correoCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tituloLibro = new javax.swing.JTextField();
        codigoLibro = new javax.swing.JTextField();
        stockLibro = new javax.swing.JTextField();
        isbnLibro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        verificaLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        paguinasLibro = new javax.swing.JTextField();
        autor = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFcliente = new javax.swing.JTextField();
        jTFLibroId = new javax.swing.JTextField();
        jTFEjemplarId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fechaPrestamo = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTFCodigoP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fechaLimite = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblCodigoCancelar = new javax.swing.JLabel();
        txtCodigoCancelar = new javax.swing.JTextField();
        btnValidarCancelar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtInfoCancelar = new javax.swing.JScrollPane();
        txtCancelar = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        lblCedulaCancelar = new javax.swing.JLabel();
        txtCedulaCancelar = new javax.swing.JTextField();
        lblTituloCancelar = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanel4.setToolTipText("");

        jLabel1.setText("Nombres: ");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Telefonos:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Identificador:");

        idCliente.setEnabled(false);
        idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteActionPerformed(evt);
            }
        });

        nombreCliente.setEnabled(false);

        apellidoCliente.setEnabled(false);

        direccionCliente.setEnabled(false);

        telefonoCliente.setEnabled(false);

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jLabel10.setText("Cedula");

        correoCliente.setEnabled(false);
        correoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(direccionCliente))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(telefonoCliente))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnValidar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jLabel7.setText("ISBN");

        jLabel8.setText("Stock");

        jLabel9.setText("Titulo:");

        jLabel11.setText("Codigo:");

        tituloLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloLibroActionPerformed(evt);
            }
        });

        codigoLibro.setEnabled(false);
        codigoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoLibroActionPerformed(evt);
            }
        });

        stockLibro.setEnabled(false);
        stockLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockLibroActionPerformed(evt);
            }
        });

        isbnLibro.setEnabled(false);
        isbnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnLibroActionPerformed(evt);
            }
        });

        jLabel12.setText("Paginas");

        verificaLibro.setText("Verificar Libro");
        verificaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaLibroActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "ID", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel13.setText("Autor");

        paguinasLibro.setEnabled(false);
        paguinasLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paguinasLibroActionPerformed(evt);
            }
        });

        autor.setEnabled(false);
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(isbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(codigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paguinasLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(autor)
                            .addComponent(stockLibro)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(verificaLibro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(stockLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(codigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(paguinasLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(autor))
                .addGap(18, 18, 18)
                .addComponent(verificaLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel14.setText("Codigo del cliente");

        jLabel16.setText("Codigo del libro");

        jLabel15.setText("Codigo del ejemplar");

        jTFcliente.setEnabled(false);

        jTFLibroId.setEnabled(false);

        jTFEjemplarId.setEnabled(false);

        jLabel18.setText("Fecha de Prestamo");

        jLabel17.setText("Fecha de Devolucion Limite");

        jButton1.setText("Generar Prestamo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTFCodigoP.setEnabled(false);

        jLabel19.setText("Codigo del prestamo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFLibroId, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFEjemplarId, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jTFCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTFcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTFLibroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTFEjemplarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Prestamo", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        lblCodigoCancelar.setText("Código del ejemplar:");

        txtCodigoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCancelarActionPerformed(evt);
            }
        });

        btnValidarCancelar.setText("Validar");
        btnValidarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarCancelarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar préstamo");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCancelar.setColumns(20);
        txtCancelar.setRows(5);
        txtInfoCancelar.setViewportView(txtCancelar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtInfoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnValidarCancelar)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCodigoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoCancelar))
                .addGap(34, 34, 34)
                .addComponent(btnValidarCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInfoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(20, 20, 20))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanel5.setToolTipText("");

        lblCedulaCancelar.setText("Cédula del cliente:");

        txtCedulaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(lblCedulaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCedulaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaCancelar)
                    .addComponent(txtCedulaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lblTituloCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloCancelar.setText("CANCELACIÓN DE PRÉSTAMOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(822, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTituloCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTituloCancelar)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancelar Prestamo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paguinasLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paguinasLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paguinasLibroActionPerformed

    private void verificaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaLibroActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();

        if (tituloLibro.getText().isEmpty()) {
            JOptionPane.showInternalMessageDialog(null, "Asegurese de ingresar el titulo del libro");
        } else {
            // consulta hacia la base de datos
            try {
                Statement sql = ConexionSQL.getConexion().createStatement();
                SqlCrudLibroByTitulo sqlCrudLibroByTitulo = new SqlCrudLibroByTitulo(ConexionSQL.getConexion());

                List<Libro> libros = sqlCrudLibroByTitulo.read(tituloLibro.getText());

                //verificar que exista el libro solicitado
                if (libros.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "no se han encontrado el libro especificado");
                } else {
                    //llenar los campos con la info del LIBRO
                    libroPrestamo = libros.get(0);
                    ejemplarPrestamo = null;
                    jTFEjemplarId.setText("");
                    autor.setText(libroPrestamo.getAutor());
                    codigoLibro.setText(libroPrestamo.getIdLibro());
                    isbnLibro.setText(libroPrestamo.getISBN());
                    paguinasLibro.setText(String.valueOf(libroPrestamo.getPaginas()));
                    stockLibro.setText(String.valueOf(libroPrestamo.getStock()));
                    auxiliarCodigoLibro = String.valueOf(libroPrestamo.getPaginas());
                    jTFLibroId.setText(libroPrestamo.getIdLibro());
                    
                    ejemplaresEncontrados = new SqlCrudEjemplarByLibroId(ConexionSQL.getConexion()).read(libroPrestamo.getIdLibro());
//                    verificar que existan ejemplares disponibles
                    modeloTabla.setRowCount(0);
                    if (ejemplaresEncontrados.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Actualmente no existen ejemplares disponibles del libro: " + tituloLibro.getText());
                    } else {
                        Object[] fila = new Object[tabla.getColumnCount()];
                        for(Ejemplar ej: ejemplaresEncontrados){
                            fila[0] = ej.getLibro().getTitulo();
                            fila[1] = ej.getIdEjemplar();
                            fila[2] = ej.getEstadoEjemplar();
                            modeloTabla.addRow(fila);
                        }
                    }

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
                Logger.getLogger(InterfazPrestamos.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_verificaLibroActionPerformed

    private void isbnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnLibroActionPerformed

    private void stockLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockLibroActionPerformed

    private void codigoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoLibroActionPerformed

    private void tituloLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloLibroActionPerformed

    private void correoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoClienteActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // poner consulta a la base de datos para verificar que el usuario esta registrado mediante el numero de cedula

        if (txtCedula.getText().isEmpty()) {
            JOptionPane.showInternalMessageDialog(null, "Asegurese de ingresar la cedula del cliente");
        } else {
            // consulta hacia la base de datos
            try {
                
                //LuisM: Se reemplazo la consulta SQL en seco por una implementación
                //Crud dedicada para cliente (Homogenizacion,mantenimiento)
                
                SqlCrudClienteByCI sqlCrudCliente = new SqlCrudClienteByCI(ConexionSQL.getConexion());
                //Statement sql = ConexionSQL.getConexion().createStatement();// DEL
                List<Cliente> clientesResultados = sqlCrudCliente.read(txtCedula.getText());
                
                // String consulta = "Select count(*) from baseBiblioteca.dbo.CLIENTES where cicliente = '" + txtCedula.getText() + "'";// DEL

                //ResultSet resultado = sql.executeQuery(consulta); //DEL
                //resultado.next(); //DEL

                //verificar que exista el cliente cuya cedula se ingreso
                if (clientesResultados.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "no se han encontrado cleintes con el numero de decula especificado");
                } else {
                    clienteValido = true;
                    clientePrestamo = clientesResultados.get(0);

                    nombreCliente.setText(clientePrestamo.getNombre());
                    apellidoCliente.setText(clientePrestamo.getApellido());
                    direccionCliente.setText(clientePrestamo.getDireccion());
                    telefonoCliente.setText(clientePrestamo.getTelefono());
                    idCliente.setText(String.valueOf(clientePrestamo.getIdCliente()));
                    correoCliente.setText(clientePrestamo.getCorreo());
                    auxiliarCodigoCliente = String.valueOf(clientePrestamo.getIdCliente()); //Discrepancia tipo de dato
                    jTFcliente.setText(String.valueOf(clientePrestamo.getIdCliente()));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    private void txtCodigoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCancelarActionPerformed

    private void txtCedulaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCancelarActionPerformed

    private void btnValidarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarCancelarActionPerformed
        //Verificacion de datos de entrada
        java.sql.Connection connection = ConexionSQL.getConexion();
        cedulaCancelar = txtCedulaCancelar.getText();
        codigoCancelar = txtCodigoCancelar.getText();
        if (cedulaCancelar.isEmpty() || codigoCancelar.isEmpty()) {
            JOptionPane.showInternalMessageDialog(null, "Asegurese de ingresar los datos requeridos");
        } else {
            try {
                clienteCancelar = new SqlCrudClienteByCI(connection).read(txtCedulaCancelar.getText()).get(0);
                ejemplarCancelar = new SqlCrudEjemplar(connection).read(Integer.parseInt(txtCodigoCancelar.getText())).get(0);
                Triplet<String,String,Integer> key = new Triplet<>(String.valueOf(clienteCancelar.getIdCliente()),ejemplarCancelar.getLibro().getIdLibro(),ejemplarCancelar.getIdEjemplar());
                List<Prestamo> todosPrestamos = new SqlCrudPrestamoByFields(connection).read(key);
                for(Prestamo p: todosPrestamos)
                    if(p.getFechaDevolucion()==null)
                        prestamosCancelar.add(p);
                //Impresion de los datos del prestamo
                
                for(Prestamo p: prestamosCancelar){
                        String dayBefore = p.getFechaVencimiento().toString();
                        txtCancelar.setText("\tDATOS DEL PRÉSTAMO A CANCELAR\n"
                        + "Cédula del Cliente: " + String.valueOf(p.getCliente().getCedula())
                        + "\nCódigo del libro: " + p.getLibro().getIdLibro()
                        + "\nCódigo del ejemplar: " + String.valueOf(p.getEjemplar().getIdEjemplar())
                        + "\nFecha de incio del préstamo: " + p.getFechaGeneracion().toString()
                        + "\nFecha establecida para la devolución: " + p.getFechaVencimiento().toString()
                        + "\nFecha actual: " + LocalDateTime.now()
                        + "\nMulta por retraso: " + calcularMulta(dayBefore));
                }
                

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "¡No se encontraron préstamos con los datos ingresados!",
                        "Error: Cancelar préstamo", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnValidarCancelarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // CANCELACION DEL PRESTAMO (DELETE ON dbo.PRESTAMO)
        JOptionPane.showConfirmDialog(null, "Está apunto de cancelar el préstamo", "Alerta: Cancelar préstamo",
                JOptionPane.WARNING_MESSAGE);
        try {
            // Cancelación de un préstamo
            java.sql.Connection connection = ConexionSQL.getConexion();
            SqlCrudPrestamoById sqlCrudPrestamoById = new SqlCrudPrestamoById(connection);
            for(Prestamo p: prestamosCancelar){
                p.setFechaDevolucion(Date.from(Instant.now()));
                sqlCrudPrestamoById.update(p);
            }
            //Impresion de mensaje de confirmación 
            txtCancelar.setText("\t¡PRÉSTAMO CANCELADO!\n"
                    + "El préstamo con datos: \n"
                    + "     Cédula del Cliente: " + cedulaCancelar
                    + "\n     Código del libro: " + codigoCancelar
                    + "\n se canceló de manera exitosa.");

            //Borrado de datos de entrada
            txtCedulaCancelar.setText("");
            txtCodigoCancelar.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "¡No se pudo cancelar el préstamo!",
                    "Error: Cancelar préstamo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // pasar la info del ejemplar a la interfaz de prestamo para generar
        int fila = tabla.getSelectedRow();
        ejemplarPrestamo = ejemplaresEncontrados.get(fila);
        jTFEjemplarId.setText(String.valueOf(ejemplarPrestamo.getIdEjemplar()));
    }//GEN-LAST:event_tablaMouseClicked

    // private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    //     // TODO add your handling code here:
    //     buscarCedula = txtCedula.getText();
    //     buscarCodigoLibro = txtCodigoTexto.getText();
    //     if (buscarCedula.isEmpty() || buscarCodigoLibro.isEmpty()) {
    //         JOptionPane.showInternalMessageDialog(null, "Asegurese de ingresar los datos requeridos");
    //     } else {
    //         try {
    //             // Verificación de la existencia del prestamo 
    //             Statement sql = ConexionSQL.getConexion().createStatement();
    //             //Sentencia para consulta en la tabla PRESTAMO
    //             String consulta = "Select * from baseBiblioteca.dbo.PRESTAMO where "
    //                     + "CODIGOCLIENTE = '" + buscarCedula + "' and CODEJEMPLAR = "
    //                     + Integer.parseInt(buscarCodigoLibro);
    //             ResultSet resultado = sql.executeQuery(consulta);
    //             resultado.next();

    //             //Impresion de los datos del prestamo
    //             txtInformacionRegistrada.setText("\tDatos Ingresados Correctamente EL PRESTAMO EXISTE\n"
    //                     + "Cédula del Cliente: " + resultado.getString("CODIGOCLIENTE")
    //                     + "\nCódigo del libro: " + resultado.getString("CODIGOLIBRO")
    //                     + "\nCódigo del ejemplar: " + resultado.getString("CODEJEMPLAR")
    //                     + "\nFecha de incio del préstamo: " + resultado.getString("FECHAPRESTAMO")
    //                     + "\nFecha establecida para la devolución: " + resultado.getString("FECHADEVOLUCION")
    //                     + "\nFecha actual: " + LocalDateTime.now());
                
    //             verificacionConsulta = 1;

    //         } catch (SQLException ex) {
    //             JOptionPane.showMessageDialog(null, "¡No se encontraron préstamos con los datos ingresados!",
    //                     "Error Consulta", JOptionPane.ERROR_MESSAGE);
    //             verificacionConsulta = 0;
    //         }
    //     }
    // }//GEN-LAST:event_btnConsultarActionPerformed

    // private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    //     // TODO add your handling code here:
    //     String fFinalModificada = "";
    //     if (verificacionConsulta == 1){
    //         try {
    //         //Verificación de la existencia del prestamo 
    //         Statement sql = ConexionSQL.getConexion().createStatement();
    //         SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
    //         fFinalModificada = ff.format(dateFechaModificada.getCalendar().getTime());
            
    //         String consulta = "UPDATE * from baseBiblioteca.dbo.PRESTAMO SET "
    //                     + "FECHADEVOLUCION = '" + fFinalModificada + "' WHERE"
    //                     + "CODIGOCLIENTE = '" + buscarCedula + "' and CODEJEMPLAR = "
    //                     + Integer.parseInt(buscarCodigoLibro);
    //         ResultSet resultado = sql.executeQuery(consulta);
    //         resultado.next();
            
    //         //Impresion de los datos del prestamo
    //             txtInformacioModificada.setText("\tDatos Ingresados Correctamente EL PRESTAMO EXISTE\n"
    //                     + "Cédula del Cliente: " + resultado.getString("CODIGOCLIENTE")
    //                     + "\nCódigo del libro: " + resultado.getString("CODIGOLIBRO")
    //                     + "\nCódigo del ejemplar: " + resultado.getString("CODEJEMPLAR")
    //                     + "\nFecha de incio del préstamo: " + resultado.getString("FECHAPRESTAMO")
    //                     + "\nFecha establecida para la devolución: " + resultado.getString("FECHADEVOLUCION")
    //                     + "\nFecha actual PRUEBA: " + LocalDateTime.now());

    //         } catch (SQLException ex) {
    //             JOptionPane.showMessageDialog(null, "¡No se actualizar la información!",
    //                         "Error Modificacion", JOptionPane.ERROR_MESSAGE);
    //                 verificacionConsulta = 0;
    //         }
    //     }else{
    //         JOptionPane.showMessageDialog(null, "¡No existe el registro, Modificacion INVALIDA!",
    //                         "Error Modificacion", JOptionPane.ERROR_MESSAGE);
    //                 verificacionConsulta = 0;
            
    //     }
            
        
    // }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.show(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.sql.Connection connection = ConexionSQL.getConexion();
        if(libroPrestamo==null) return;
        if(clientePrestamo==null) return;
        if(ejemplarPrestamo==null) return;
        if(fechaPrestamo.getDate()==null) return;
        if(fechaLimite.getDate()==null) return;
        try {
            Prestamo prestamo = new Prestamo(Prestamo.sQLIndexIdPrestamo.pop(), clientePrestamo, libroPrestamo, ejemplarPrestamo, fechaPrestamo.getDate(), fechaLimite.getDate());
            SqlCrudPrestamoById sqlCrudPrestamoById = new SqlCrudPrestamoById(connection);
            ejemplarPrestamo.setEstadoEjemplar("Prestado");
            new SqlCrudEjemplarByLibroId(connection).update(ejemplarPrestamo);
            sqlCrudPrestamoById.create(prestamo);
            JOptionPane.showMessageDialog(null, "Regsitro Exitoso");
            this.show(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JTextField autor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnValidarCancelar;
    private javax.swing.JTextField codigoLibro;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JTextField direccionCliente;
    private com.toedter.calendar.JDateChooser fechaLimite;
    private com.toedter.calendar.JDateChooser fechaPrestamo;
    private javax.swing.JTextField idCliente;
    private javax.swing.JTextField isbnLibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigoP;
    private javax.swing.JTextField jTFEjemplarId;
    private javax.swing.JTextField jTFLibroId;
    private javax.swing.JTextField jTFcliente;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCedulaCancelar;
    private javax.swing.JLabel lblCodigoCancelar;
    private javax.swing.JLabel lblTituloCancelar;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField paguinasLibro;
    private javax.swing.JTextField stockLibro;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefonoCliente;
    private javax.swing.JTextField tituloLibro;
    private javax.swing.JTextArea txtCancelar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaCancelar;
    private javax.swing.JTextField txtCodigoCancelar;
    private javax.swing.JScrollPane txtInfoCancelar;
    private javax.swing.JButton verificaLibro;
    // End of variables declaration//GEN-END:variables
}
